### ISSUE TITLE
State management alternatives

### ISSUE THREAD

**Issue by DmitryEfimenko** [avatsaev/angular-learning-resources#2]
This study guide covers NgRx in detail. However, that's not the only one popular state management solution out there.
I think [Akita](https://github.com/datorama/akita) should certainly be mentioned. Here are [blogs](https://netbasal.gitbook.io/akita/entity-store/blog-posts). Some of them could probably be mentioned

Also [NgXS](https://github.com/ngxs/store) probably worth a mention

**Comment by avatsaev** [comment]
Thanks, I'll add them to the list.
